### ISSUE TITLE
Not Enough Templates [Framework Developer Job Application]

### ISSUE THREAD

**Issue by TEMHITHORPHE** [MoterHaker/opensubmitter#14]
Morning folks, the name is Temi.

A little birdie told me you guys needed help on this project, and I believe I am the answer, and I'm ready to jump right in and start work right away, be it extending the framework or building additional templates, to which I have to say, great work so far, it looks promising, maybe it's time someone finally give Phantombuster a run for their money.

I am open to talk and discuss about how we go forward from here.

Yours sincerely, Temi.

**Comment by MoterHaker** [comment]
Hi, yes I'm aware of that. I've just started and collecting the template requests from customers.

Drop a line to dev (@) opensubmitter.com , tell about yourself.

**Comment by TEMHITHORPHE** [comment]
Thank you for the prompt response @MotorHacker, I just lowered the anchor
at the specified email address.

Here's to hopeful long term partnership 🍷.
