### ISSUE TITLE
Как подменять fingerprint?

### ISSUE THREAD

**Issue by dixakman** [MoterHaker/opensubmitter#18]
Добрый день, приведите пример как подменять fingerprint

**Comment by MoterHaker** [comment]
Смотря какая задача стоит. Если сгенерировать уникальный canvas, то пример тут:

https://stackoverflow.com/questions/57737610/puppeteer-fingerprint-simulation
(отдавать рандомное изображение)

В шаблоне вызов будет `await this.page.evaluateOnNewDocument(() ...`

**Comment by dixakman** [comment]
> Смотря какая задача стоит. Если сгенерировать уникальный canvas, то пример тут:
> 
> https://stackoverflow.com/questions/57737610/puppeteer-fingerprint-simulation (отдавать рандомное изображение)
> 
> В шаблоне вызов будет `await this.page.evaluateOnNewDocument(() ...`

А webrts, а dns подменять и прочее? пупеттер очень слаб в анонимности

А как клики "живые" делать, с эмуляцией?

**Comment by MoterHaker** [comment]
Да также в гугле ищем что нужно и применяем.

```
await this.page.evaluate(async() => {
    let element = document.getElementsByTagName("body");
    const event = new MouseEvent('mouseover', {
        view: window,
        bubbles: true,
        cancelable: true,
        clientX: Math.round(Math.random() * 300),
        clientY: Math.round(Math.random() * 300)
    });
    element.dispatchEvent(event);
});
```

Какая у вас задача?

**Comment by MoterHaker** [comment]
>пупеттер очень слаб в анонимности

А что не слабо в анонимности? Можно в OpenSubmitter включить любой JS модуль.

**Comment by dixakman** [comment]
> Да также в гугле ищем что нужно и применяем.
> 
> ```
> await this.page.evaluate(async() => {
>     let element = document.getElementsByTagName("body");
>     const event = new MouseEvent('mouseover', {
>         view: window,
>         bubbles: true,
>         cancelable: true,
>         clientX: Math.round(Math.random() * 300),
>         clientY: Math.round(Math.random() * 300)
>     });
>     element.dispatchEvent(event);
> });
> ```
> 
> Какая у вас задача?

К примеру гугл подобные события "видит", и прослушивает, я молчу про другие сервисы, нужен какой-то другой метод взаимодействия... возможно даже напрямую с инстансом, как это делает зенка или бас

**Comment by dixakman** [comment]
> > Да также в гугле ищем что нужно и применяем.
> > ```
> > await this.page.evaluate(async() => {
> >     let element = document.getElementsByTagName("body");
> >     const event = new MouseEvent('mouseover', {
> >         view: window,
> >         bubbles: true,
> >         cancelable: true,
> >         clientX: Math.round(Math.random() * 300),
> >         clientY: Math.round(Math.random() * 300)
> >     });
> >     element.dispatchEvent(event);
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Какая у вас задача?
> 
> К примеру гугл подобные события "видит", и прослушивает, я молчу про другие сервисы, нужен какой-то другой метод взаимодействия... возможно даже напрямую с инстансом, как это делает зенка или бас

Ни один из них не помогает обойти проверти pixelscan

**Comment by MoterHaker** [comment]
Пример того, что может обходить - в студию. Не обходит и не обходит, претензии направляйте в Puppeteer и Google. Найдем что-то рабочее - будем использовать. А так у приложения нет задачи обходить pixelscan, но для 95% других сайтов отлично подойдет.
