### ISSUE TITLE
Application for a job.

### ISSUE THREAD

**Issue by sk0le** [MoterHaker/opensubmitter#23]
I saw job posting on upwork.
Unfortunately I don't have enough connects to apply, so I'm writing here in hope that you will leave email for me to send cover letter, resume etc...

**Comment by MoterHaker** [comment]
Hi, post a link here to your examples with Puppeteer at Github.

**Comment by sk0le** [comment]
Okay, I will write cover letter here and also attach my resume.

Hi, my name is Amel Islamovic. I'm 18 year old high school student who has been captivated by the world of programming since a young age. I am writing to express my strong interest in joining this project. Unfortunately I don't have experience with Puppeteer exactly, but I'm more than willing to learn about it. I've worked scraping web, my last project on upwork was exactly that, but in Go [Upwork profile](https://www.upwork.com/freelancers/~01894bc6d89d081535?viewMode=1). You can see that I've worked with a lot of typescript, but also I was competing in state competition in competitive programming (C++). 

I hope that we will continue this conversion outside github.

[Amel Islamovic English.pdf](https://github.com/MoterHaker/opensubmitter/files/12475204/Amel.Islamovic.English.pdf)

**Comment by MoterHaker** [comment]
Not interested.
